repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: external-dns
    namespace: {{ requiredEnv "NAMESPACE_KUBEADDONS" }}
    chart: bitnami/external-dns
    version: 5.1.1
    values:
      - provider: azure
        azure:
          resourceGroup: {{ requiredEnv "AZ_RESOURCE_GROUP" }}
          tenantId: {{ requiredEnv "AZ_TENANT_ID" }}
          subscriptionId: {{ requiredEnv "AZ_SUBSCRIPTION_ID" }}
          useManagedIdentityExtension: true
        logLevel: {{ env "EXTERNALDNS_LOG_LEVEL" | default "debug" }}
        domainFilters:
          - {{ requiredEnv "AZ_AZ_DNS_DOMAIN" }}
        txtOwnerId: external-dns