ingress:
  enabled: true
  hostname: sonarqube.aks.ez-lab.xyz
  ingressClassName: "nginx"
  path: /
  servicePort: http
sonarqubeUsername: user
sonarqubePassword: "delltech"
sonarqubeEmail: fjacquet@ljfch.onmicrosoft.com
service:
  type: LoadBalancer
