ingressRoute:
  dashboard:
    enabled: true
    matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    entryPoints: ["traefik"]
ports:
  websecure:
    tls:
      enabled: true
      domains:
        - main: aks.ez-lab.xyz
          sans:
            - apps.aks.ez-lab.xyz
            - demo.aks.ez-lab.xyz
            - gitlab.aks.ez-lab.xyz
            - grafana.aks.ez-lab.xyz
            - jenkins.aks.ez-lab.xyz
            - keycloak.aks.ez-lab.xyz
            - minio.aks.ez-lab.xyz
            - prometheus.aks.ez-lab.xyz
            - redis.aks.ez-lab.xyz
            - sonarqube.aks.ez-lab.xyz
            - whoami.aks.ez-lab.xyz
            - wiki.aks.ez-lab.xyz
